on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install deps
        run: |
          go get .

      - name: Run tests
        run: go test ./...

      - name: Build artifacts
        run: scripts/build.sh
        env:
          INPUT_GOOS: "linux,darwin,windows"
          INPUT_GOARCH: "amd64,arm64"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rcidf
          path: dist/rcidf*

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags')
        with:
          files: |
            dist/*